var res = {
    start_n_png : "res/start_n.png",
    start_s_png : "res/start_s.png",
    testcake_png : "res/TestCake/testcake.png",
    testcake_plist : "res/TestCake/testcake.plist",
    oven_png : "res/oven.png",
    startmenuBG_png : "res/Backgrounds/startmenuBG.png",
    playBG_png : "res/Backgrounds/playBG.png",
    gameoverBG_png : "res/Backgrounds/gameoverBG.png",
    differentBG_png : "res/Backgrounds/differentBG.png",
    testcakepattern1_png : "res/TestCake/testcakepattern1.png",
    testcakepattern2_png : "res/TestCake/testcakepattern2.png",
    testcakepattern3_png : "res/TestCake/testcakepattern3.png",
    testcakepattern4_png : "res/TestCake/testcakepattern4.png",
    red_button10_png : "res/UI/red_button10.png",
    red_button13_png : "res/UI/red_button13.png",
    red_sliderDown_png : "res/UI/red_sliderDown.png",
    ovenBarBackground_png : "res/UI/ovenBarBackground.png",
    bread_png : "res/Bread/bread.png",
    bread_plist : "res/Bread/bread.plist",
    // Menu Pictures
    Pictures_Menu_stdPlay_png : "res/UI/stdPlay.png",
    Pictures_Menu_actPlay_png : "res/UI/actPlay.png",
    Pictures_Menu_stdHiScores_png : "res/UI/stdHiScores.png",
    Pictures_Menu_actHiScores_png : "res/UI/actHiScores.png",
    Pictures_Menu_stdDirections_png : "res/UI/stdDirections.png",
    Pictures_Menu_actDirections_png : "res/UI/actDirections.png",
    Pictures_Menu_stdOptions_png : "res/UI/stdOptions.png",
    Pictures_Menu_actOptions_png : "res/UI/actOptions.png",
    Pictures_Menu_stdExit_png : "res/UI/stdExit.png",
    Pictures_Menu_actExit_png : "res/UI/actExit.png",
    Pictures_Menu_stdReturn_png : "res/UI/stdReturn.png",
    Pictures_Menu_actReturn_png : "res/UI/actReturn.png"

};

var g_resources = [
    res.start_n_png,
    res.start_s_png,
    res.testcake_png,
    res.testcake_plist,
    res.oven_png,
    res.startmenuBG_png,
    res.playBG_png,
    res.gameoverBG_png,
    res.differentBG_png,
    res.testcakepattern1_png,
    res.testcakepattern2_png,
    res.testcakepattern3_png,
    res.testcakepattern4_png,
    res.red_button10_png,
    res.red_button13_png,
    res.red_sliderDown_png,
    res.ovenBarBackground_png,
    res.bread_png,
    res.bread_plist,
    // Menu Pictures
    res.Pictures_Menu_stdPlay_png,
    res.Pictures_Menu_actPlay_png,
    res.Pictures_Menu_stdHiScores_png,
    res.Pictures_Menu_actHiScores_png,
    res.Pictures_Menu_stdDirections_png,
    res.Pictures_Menu_actDirections_png,
    res.Pictures_Menu_stdOptions_png,
    res.Pictures_Menu_actOptions_png,
    res.Pictures_Menu_stdExit_png,
    res.Pictures_Menu_actExit_png,
    res.Pictures_Menu_stdReturn_png,
    res.Pictures_Menu_actReturn_png

];