var res = {
    start_n_png : "res/start_n.png",
    start_s_png : "res/start_s.png",
    testcake_png : "res/TestCake/testcake.png",
    testcake_plist : "res/TestCake/testcake.plist",
    oven_png : "res/oven.png",
    startmenuBG_png : "res/Backgrounds/startmenuBG.png",
    playBG_png : "res/Backgrounds/playBG.png",
    gameoverBG_png : "res/Backgrounds/gameoverBG.png",
    differentBG_png : "res/Backgrounds/differentBG.png",
    testcakepattern1_png : "res/TestCake/testcakepattern1.png",
    testcakepattern2_png : "res/TestCake/testcakepattern2.png",
    testcakepattern3_png : "res/TestCake/testcakepattern3.png",
    testcakepattern4_png : "res/TestCake/testcakepattern4.png",
    red_button10_png : "res/UI/red_button10.png",
    red_button13_png : "res/UI/red_button13.png",
    red_sliderDown_png : "res/UI/red_sliderDown.png",
    bread_png : "res/Bread/bread.png",
    bread_plist : "res/Bread/bread.plist"
};

var g_resources = [
    res.start_n_png,
    res.start_s_png,
    res.testcake_png,
    res.testcake_plist,
    res.oven_png,
    res.startmenuBG_png,
    res.playBG_png,
    res.gameoverBG_png,
    res.differentBG_png,
    res.testcakepattern1_png,
    res.testcakepattern2_png,
    res.testcakepattern3_png,
    res.testcakepattern4_png,
    res.red_button10_png,
    res.red_button13_png,
    res.red_sliderDown_png,
    res.bread_png,
    res.bread_plist
];